import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AuditOutlined, BookOutlined, DashboardOutlined, KeyOutlined, LogoutOutlined, MessageOutlined, SafetyCertificateOutlined, TeamOutlined } from '@ant-design/icons';
import { Alert, App as AntApp, Button, Card, Col, ConfigProvider, Form, Input, Layout, Menu, Modal, Row, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { client } from './api';
import './style.css';

type Admin = { username: string; role: string; schoolId?: string | null };
const statusColors: Record<string, string> = { pending: 'gold', approved: 'green', rejected: 'red', offline: 'default' };
const statusText: Record<string, string> = { pending: '待审核', approved: '已通过', rejected: '已驳回', offline: '已下架' };

function Login({ onLogin }: { onLogin: (admin: Admin) => void }) {
  const [loading, setLoading] = useState(false);
  const demoLogin = import.meta.env.DEV ? { username: 'admin', password: 'Weculture@2026' } : undefined;
  const submit = async (values: { username: string; password: string }) => { setLoading(true); try { const result = await client.post('/admin/auth/login', values); localStorage.setItem('adminToken', result.token); onLogin(result.admin); } catch (error) { message.error((error as Error).message); } finally { setLoading(false); } };
  return <main className="login"><section className="login-art"><div className="brand">Weculture</div><h1>让校园文化运营<br />有序发生</h1><p>单校内测运营后台</p></section><Card className="login-card" bordered={false}><Typography.Title level={3}>管理员登录</Typography.Title><Typography.Paragraph type="secondary">使用学校或平台管理员账号进入。</Typography.Paragraph><Form layout="vertical" onFinish={submit} initialValues={demoLogin}><Form.Item name="username" label="账号" rules={[{ required: true }]}><Input size="large" /></Form.Item><Form.Item name="password" label="密码" rules={[{ required: true }]}><Input.Password size="large" /></Form.Item><Button htmlType="submit" type="primary" size="large" block loading={loading}>登录后台</Button></Form>{import.meta.env.DEV && <Alert className="login-note" message="本地演示账号已预填，生产构建不会包含这些登录信息。" type="info" showIcon />}</Card></main>;
}

function Dashboard() {
  const [data, setData] = useState<any>(); useEffect(() => { void client.get('/admin/dashboard').then(setData).catch((e) => message.error(e.message)); }, []);
  if (!data) return <div className="loading">正在读取运营概览...</div>;
  return <><Typography.Title level={2}>运营工作台</Typography.Title><Typography.Paragraph type="secondary">优先处理待审核内容，所有管理操作均会记录审计日志。</Typography.Paragraph><Row gutter={[18, 18]}><Metric title="待审核内容" value={data.pendingPosts} tone="orange" /><Metric title="已发布内容" value={data.approvedPosts} tone="green" /><Metric title="认证成员" value={data.users} tone="blue" /><Metric title="进行中活动" value={data.activeEvents} tone="brown" /></Row><Card title="近期管理操作" className="table-card"><Table size="middle" pagination={false} dataSource={data.recentAudits} rowKey="id" columns={[{ title: '时间', dataIndex: 'createdAt', render: (x: string) => new Date(x).toLocaleString() }, { title: '操作', dataIndex: 'action' }, { title: '资源', render: (_: unknown, r: any) => `${r.resourceType} / ${r.resourceId.slice(0, 8)}` }, { title: '结果', dataIndex: 'result', render: (x: string) => <Tag color="green">{x}</Tag> }]} /></Card></>;
}
function Metric({ title, value, tone }: { title: string; value: number; tone: string }) { return <Col xs={24} sm={12} lg={6}><Card className={`metric ${tone}`}><Statistic title={title} value={value} /></Card></Col>; }

function Posts() {
  const [posts, setPosts] = useState<any[]>([]); const [status, setStatus] = useState('pending'); const [reason, setReason] = useState(''); const [selected, setSelected] = useState<any>();
  const load = () => client.get<any[]>(`/admin/posts?status=${status}`).then(setPosts).catch((e) => message.error(e.message)); useEffect(() => { void load(); }, [status]);
  const review = async (next: string) => { if (!selected) return; try { await client.post(`/admin/posts/${selected.id}/review`, { status: next, reason }); message.success(next === 'approved' ? '内容已通过' : next === 'rejected' ? '内容已驳回' : '内容已下架'); setSelected(undefined); setReason(''); load(); } catch (e) { message.error((e as Error).message); } };
  return <><Typography.Title level={2}>内容审核</Typography.Title><Space className="toolbar"><Select value={status} onChange={setStatus} options={[{ value: 'pending', label: '待审核' }, { value: 'approved', label: '已通过' }, { value: 'rejected', label: '已驳回' }, { value: 'offline', label: '已下架' }]} /></Space><Card className="table-card"><Table dataSource={posts} rowKey="id" pagination={{ pageSize: 8 }} columns={[{ title: '标题', dataIndex: 'title' }, { title: '类型', dataIndex: 'type', render: (x: keyof typeof statusText) => ({ dynamic: '动态', event: '活动', market: '闲置' } as Record<string, string>)[x] }, { title: '范围', dataIndex: 'visibility', render: (x: string) => x === 'school' ? '校内' : '平台' }, { title: '状态', dataIndex: 'status', render: (x: string) => <Tag color={statusColors[x]}>{statusText[x]}</Tag> }, { title: '提交时间', dataIndex: 'createdAt', render: (x: string) => new Date(x).toLocaleString() }, { title: '操作', render: (_: unknown, r: any) => <Button type="link" onClick={() => setSelected(r)}>查看与处理</Button> }]} /></Card><Modal title="审核内容" open={Boolean(selected)} onCancel={() => setSelected(undefined)} footer={null}><Typography.Title level={4}>{selected?.title}</Typography.Title><Typography.Paragraph>{selected?.content}</Typography.Paragraph><Tag>{selected?.tag}</Tag><Form layout="vertical" style={{ marginTop: 18 }}><Form.Item label="驳回原因（驳回时必填）"><Input.TextArea value={reason} onChange={(e) => setReason(e.target.value)} rows={3} placeholder="请向用户说明处理原因" /></Form.Item><Space><Button type="primary" onClick={() => review('approved')}>审核通过</Button><Button danger onClick={() => review('rejected')}>驳回</Button><Button onClick={() => review('offline')}>下架</Button></Space></Form></Modal></>;
}

function Invites() {
  const [rows, setRows] = useState<any[]>([]); const [form] = Form.useForm(); const load = () => client.get<any[]>('/admin/invites').then(setRows).catch((e) => message.error(e.message)); useEffect(() => { void load(); }, []); const create = async (values: any) => { try { const result = await client.post<any>('/admin/invites', values); message.success(`邀请码 ${result.code} 已创建`); form.resetFields(); void load(); } catch (e) { message.error((e as Error).message); } };
  return <><Typography.Title level={2}>邀请码与成员认证</Typography.Title><Row gutter={18}><Col xs={24} lg={8}><Card title="生成邀请码"><Form form={form} layout="vertical" onFinish={create} initialValues={{ batchName: '内测用户', maxUses: 10 }}><Form.Item name="batchName" label="批次名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="maxUses" label="可使用次数" rules={[{ required: true }]}><Input type="number" /></Form.Item><Form.Item name="expiresAt" label="有效期（可选）"><Input placeholder="2026-12-31" /></Form.Item><Button htmlType="submit" type="primary">生成邀请码</Button></Form></Card></Col><Col xs={24} lg={16}><Card title="邀请码列表"><Table dataSource={rows} rowKey="id" pagination={false} columns={[{ title: '邀请码', dataIndex: 'code', render: (x) => <Typography.Text code>{x}</Typography.Text> }, { title: '批次', dataIndex: 'batchName' }, { title: '使用量', render: (_, r) => `${r.usedCount} / ${r.maxUses}` }, { title: '有效期', dataIndex: 'expiresAt', render: (x) => x ? new Date(x).toLocaleDateString() : '长期有效' }, { title: '状态', dataIndex: 'status', render: (x) => <Tag color="green">{x === 'active' ? '有效' : '已作废'}</Tag> }]} /></Card></Col></Row></>;
}

function ResourceManager({ kind }: { kind: 'route' | 'knowledge' }) {
  const isRoute = kind === 'route'; const endpoint = isRoute ? '/admin/routes' : '/admin/knowledge'; const [rows, setRows] = useState<any[]>([]); const [form] = Form.useForm(); const load = () => client.get<any[]>(endpoint).then(setRows).catch((e) => message.error(e.message)); useEffect(() => { void load(); }, [endpoint]); const submit = async (values: any) => { try { await client.post(endpoint, values); message.success(isRoute ? '路线已创建' : '知识答复已创建'); form.resetFields(); void load(); } catch (e) { message.error((e as Error).message); } };
  return <><Typography.Title level={2}>{isRoute ? '旅行路线管理' : '校园小C知识库'}</Typography.Title><Row gutter={18}><Col xs={24} lg={9}><Card title={isRoute ? '新建路线' : '新建答复'}><Form form={form} layout="vertical" onFinish={submit}>{isRoute ? <><Form.Item name="title" label="路线名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="destination" label="目的地" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="days" label="出行天数" rules={[{ required: true }]}><Select options={['1-3天', '4-7天', '7天以上'].map((x) => ({ value: x }))} /></Form.Item><Form.Item name="budget" label="参考价格"><Input type="number" /></Form.Item><Form.Item name="preferences" label="偏好（逗号分隔）"><Input placeholder="文化,艺术" /></Form.Item><Form.Item name="stops" label="途经地点（用 -> 分隔）"><Input /></Form.Item><Form.Item name="highlights" label="路线亮点（逗号分隔）"><Input /></Form.Item></> : <><Form.Item name="question" label="问题" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="keywords" label="关键词（逗号分隔）" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="answer" label="答复" rules={[{ required: true }]}><Input.TextArea rows={5} /></Form.Item></>}<Button type="primary" htmlType="submit">保存</Button></Form></Card></Col><Col xs={24} lg={15}><Card title={isRoute ? '已上架路线' : '已配置答复'}><Table dataSource={rows} rowKey="id" pagination={{ pageSize: 7 }} columns={isRoute ? [{ title: '路线', dataIndex: 'title' }, { title: '目的地', dataIndex: 'destination' }, { title: '天数', dataIndex: 'days' }, { title: '状态', dataIndex: 'status' }] : [{ title: '问题', dataIndex: 'question' }, { title: '关键词', dataIndex: 'keywords' }, { title: '答复', dataIndex: 'answer', ellipsis: true }, { title: '状态', dataIndex: 'status' }]} /></Card></Col></Row></>;
}

function Users() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { void client.get<any[]>('/admin/users').then(setRows).catch((e) => message.error(e.message)); }, []); return <><Typography.Title level={2}>校内成员</Typography.Title><Card className="table-card"><Table dataSource={rows} rowKey={(x) => x.membership.id} columns={[{ title: '昵称', render: (_: unknown, r: any) => r.user?.nickname || '未补全' }, { title: '认证状态', dataIndex: ['membership', 'verificationStatus'], render: () => <Tag color="green">已认证</Tag> }, { title: '加入时间', dataIndex: ['membership', 'createdAt'], render: (x: string) => new Date(x).toLocaleString() }]} /></Card></>; }

function Console({ admin, onLogout }: { admin: Admin; onLogout: () => void }) { const [key, setKey] = useState('dashboard'); const content = key === 'dashboard' ? <Dashboard /> : key === 'posts' ? <Posts /> : key === 'invites' ? <Invites /> : key === 'routes' ? <ResourceManager kind="route" /> : key === 'knowledge' ? <ResourceManager kind="knowledge" /> : <Users />; const items = [{ key: 'dashboard', icon: <DashboardOutlined />, label: '工作台' }, { key: 'posts', icon: <SafetyCertificateOutlined />, label: '内容审核' }, { key: 'invites', icon: <KeyOutlined />, label: '邀请码' }, { key: 'routes', icon: <BookOutlined />, label: '旅行路线' }, { key: 'knowledge', icon: <MessageOutlined />, label: '小C知识库' }, { key: 'users', icon: <TeamOutlined />, label: '校内成员' }]; return <Layout className="shell"><Layout.Sider breakpoint="lg" collapsedWidth="0" className="sider"><div className="logo">Weculture<span>运营后台</span></div><Menu theme="dark" mode="inline" selectedKeys={[key]} items={items} onClick={(e) => setKey(e.key)} /><div className="sider-footer"><div>{admin.username}</div><small>{admin.role === 'super_admin' ? '平台超级管理员' : '学校运营管理员'}</small><Button icon={<LogoutOutlined />} type="text" onClick={onLogout}>退出</Button></div></Layout.Sider><Layout><Layout.Header className="topbar"><span><AuditOutlined /> 所有管理操作均记录审计日志</span></Layout.Header><Layout.Content className="content">{content}</Layout.Content></Layout></Layout>; }
function Root() { const [admin, setAdmin] = useState<Admin | null>(null); const logout = () => { localStorage.removeItem('adminToken'); setAdmin(null); }; return <AntApp>{admin ? <Console admin={admin} onLogout={logout} /> : <Login onLogin={setAdmin} />}</AntApp>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><ConfigProvider locale={zhCN} theme={{ token: { colorPrimary: '#C5532E', borderRadius: 8, fontFamily: 'PingFang SC, Microsoft YaHei, sans-serif' } }}><Root /></ConfigProvider></React.StrictMode>);
